name: hello-world
run-name: ${{ github.actor }} is learning
on:
  pull_request:
    types: [opened, reopened]
jobs:
  this-is-a-job-name:
    runs-on: self-hosted
    steps:
      - name: List repository branches
        env:
          API_URL: ${{ github.api_url }}
          REPOSITORY: ${{ github.repository }}
          NCSU_GITHUB_TOKEN: ${{ secrets.NCSU_GITHUB_TOKEN }}
          OWNER: ${{ github.actor }}
        run: |
          curl --fail-with-body --silent --show-error \
            --request GET \
            --url "${API_URL}/repos/${OWNER}/${REPOSITORY}/branches" \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer ${NCSU_GITHUB_TOKEN}" \
            --header "X-GitHub-Api-Version: 2026-03-10"